const translations = {
    en: {
        "mascot-hero": "Welcome to my Tokyo Theme Park! Enjoy the tour!",
        "mascot-about": "Learn more about my journey from India to SAP consulting in Tokyo!",
        "mascot-experience": "This is the business district. Look at my SAP projects!",
        "mascot-skills": "Welcome to the Tech Arcade! Watch my skill bars power up!",
        "mascot-deeptech": "The Odaiba Engineering Bay! Core SAP architecture lies here.",
        "mascot-certifications": "The Shrine of Knowledge. My top certifications are kept here.",
        "mascot-contact": "Broadcasting from the Skytree! Drop me an email!",
        
        "hero-greeting": "Hi, I'm",
        "hero-name": "Dheeraj Gupta",
        "hero-title": "SAP SD Bilingual Consultant",
        "hero-subtitle": "Based in Tokyo | Expert in OTC, Data Migration and Implementation, Testing, Rollout and Support",
        "hero-activate": "Discover ➔ Prepare ➔ Explore ➔ Realize ➔ Deploy ➔ Run",
        "btn-english": "📄 English CV",
        "btn-rirekisho": "📝 履歴書 (Rirekisho)",
        "btn-shokumu": "💼 職務経歴書 (Details)",
        
        "section-about": "Self PR / My Journey",
        "about-p1": "My career started in procurement in the Indian manufacturing industry, where I spearheaded the implementation of Zoho Inventory, improving inventory turnover by 20% and reducing storage costs by 15%. This experience sparked my passion for using IT to drive business transformation, motivating me to pivot toward larger ERP systems.",
        "about-p2": "Simultaneously, I dedicated myself to mastering the Japanese language. I earned two diplomas from Delhi University's Department of East Asian Studies and passed the JLPT N2. My goal wasn't just acquiring language certifications, but deeply understanding Japanese business culture to become a valuable asset within Japanese organizations.",
        "about-p3": "At Fujitsu India, I directly supported Japanese clients. Initially challenged by technical jargon and Keigo, I overcame this by recording meetings for review and thoroughly memorizing manuals. I also successfully automated procurement workflows using UiPath RPA, cementing my belief in combining language capabilities with IT.",
        "about-p4": "Upon joining Capgemini, I immersed myself in SAP SD, self-studying foundational concepts like ATP, Pricing, and Shipping Points daily. Within six months, I was independently handling core SD configurations, and within a year, my accelerated resolution speed earned high client praise. Gaining hands-on experience across the entire SAP implementation lifecycle—Rollouts, Data Migrations, UAT, and Support—on major projects like Yamaha Music, Panasonic, and GC Dental remains my greatest professional asset.",
        "about-p5": "In March 2026, I relocated to Tokyo and joined IndoSakura Software Japan. Transitioning from remote support to an on-site environment has given me the opportunity to engage directly with local clients. As I continue to grow, I am actively learning SAP MM and SAP BTP to evolve into a multi-dimensional consultant capable of proposing comprehensive, cross-module solutions. My greatest strengths are my 'speed of learning' and 'bilingual team contribution'. I am driven by the desire to earn my team's trust and consistently deliver results.",

        "section-experience": "Experience Timeline",
        "exp-indosakura-date": "Mar 2026 - Present",
        "exp-indosakura-title": "SAP SD Bilingual Consultant",
        "exp-indosakura-company": "IndoSakura Software Japan | Tokyo",
        "exp-indosakura-b1": "Providing L2/L3 support covering core OTC processes and Pricing Procedures.",
        "exp-indosakura-b2": "Gathering bilingual requirements to map business needs into System Architecture.",
        "exp-indosakura-b3": "Resolving advanced output determination and shipping point issues.",

        "exp-capgemini-date": "Jul 2023 - Feb 2026",
        "exp-capgemini-title": "SAP SD Bilingual Consultant",
        "exp-capgemini-company": "Capgemini India (Japan Market)",
        "exp-capgemini-b1": "Tapestry: Handled production support, analyzing IDOC failures and designing User Exits.",
        "exp-capgemini-b2": "Yamaha Music: Mapped Enterprise Structure and customized Copy Control for Global Templates.",
        "exp-capgemini-b3": "Panasonic: Executed complex Legacy-to-S/4HANA Data Migrations and implemented BAPIs.",
        "exp-capgemini-b4": "GC Dental: Led Panaya UAT test cycles covering end-to-end OTC and custom RICEFW enhancements.",

        "exp-fujitsu-date": "Jan 2022 - Jul 2023",
        "exp-fujitsu-title": "Technical Service Representative",
        "exp-fujitsu-company": "Fujitsu India (Japan Market)",
        "exp-fujitsu-b1": "Supported bilingual procurement processing for global partners.",
        "exp-fujitsu-b2": "Automated PO and Quote processes using UiPath RPA.",

        "exp-gupta-date": "Aug 2017 - Apr 2019",
        "exp-gupta-title": "Procurement Executive",
        "exp-gupta-company": "Gupta Industrial Hardware | India",
        "exp-gupta-b1": "Led Zoho Inventory implementation and BP Master alignment.",
        "exp-gupta-b2": "Improved inventory turnover by 20% and slashed costs by 15%.",

        "section-skills": "Tech Arsenal",
        "skill-title-sap": "SAP Modules",
        "skill-sd": "S/4HANA SD (Sales)",
        "skill-mm": "SAP MM (Basics)",
        "skill-btp": "SAP BTP (Learning)",
        "skill-title-integration": "Integration & Testing",
        "skill-idoc": "IDOC / EDI / API",
        "skill-panaya": "Panaya UAT",
        "skill-rpa": "UiPath RPA",
        "skill-title-lang": "Languages",
        "skill-en": "English (Business)",
        "skill-ja": "Japanese (JLPT N2)",
        "skill-hi": "Hindi (Native)",

        "section-deeptech": "SAP Architecture & Processes",
        "tech-func-title": "Core Functional (SD)",
        "tech-func-list": "<ul style='text-align:left; padding-left:20px; list-style-type:square; font-size:0.95rem; line-height:1.8; margin-top:10px;'><li>Order-to-Cash (OTC)</li><li>Pricing Procedures</li><li>Enterprise Structure</li><li>BP Master</li><li>Output Determination</li><li>Copy Control</li><li>Shipping Point Determination</li><li>Sales Document Types</li><li>ATP Check</li><li>Route Determination</li><li>etc.</li></ul>",
        "tech-abap-title": "Technical & ABAP",
        "tech-abap-list": "<ul style='text-align:left; padding-left:20px; list-style-type:square; font-size:0.95rem; line-height:1.8; margin-top:10px;'><li>RICEFW Framework</li><li>BAPI Integration</li><li>BADI Implementations</li><li>User Exits</li><li>Custom Enhancements</li><li>IDOC/EDI Monitoring</li></ul>",
        "tech-cloud-title": "Cloud & Integration",
        "tech-cloud-list": "<ul style='text-align:left; padding-left:20px; list-style-type:square; font-size:0.95rem; line-height:1.8; margin-top:10px;'><li>SAP BTP</li><li>Integration Suite</li><li>Cloud Connector</li><li>J4C (Joule for Consultant)</li><li>J4D (Joule for Developer)</li><li>Third-Party API Sync</li></ul>",
        
        "section-casestudies": "Architecture Case Studies",
        "cs1-title": "Case Study 1: Global E2E OTC Flow",
        "cs1-desc": "End-to-end integration mapping from inquiry to final payment, demonstrating deep technical SAP SD architecture.",
        "cs1-n1": "Inquiry<br><span style='font-size:0.8em;opacity:0.8'>VA11</span>",
        "cs1-n2": "Quotation<br><span style='font-size:0.8em;opacity:0.8'>VA21</span>",
        "cs1-n3": "Sales Order<br><span style='font-size:0.8em;opacity:0.8'>VA01</span>",
        "cs1-n4": "Delivery<br><span style='font-size:0.8em;opacity:0.8'>VL01N</span>",
        "cs1-n5": "PGI<br><span style='font-size:0.8em;opacity:0.8'>VL02N</span>",
        "cs1-n6": "Invoice<br><span style='font-size:0.8em;opacity:0.8'>VF01</span>",
        "cs1-n7": "Payment<br><span style='font-size:0.8em;opacity:0.8'>F-28</span>",

        "modal-inq-title": "Inquiry (VA11)",
        "modal-inq-data": "<b>Concept:</b> Information gathering; customer requests price/availability without obligation.<br><br><b>Key Tables:</b><br>• <b>VBAK:</b> Header (Doc Type: IN)<br>• <b>VBAP:</b> Item Data<br>• <b>VBKD:</b> Business Data (Payment Terms)<br><br><b>T-Codes:</b> VA11, VA12, VA13, VA15",
        "modal-qt-title": "Quotation (VA21)",
        "modal-qt-data": "<b>Concept:</b> Legally binding offer with fixed pricing/validity. Price is binding on the seller.<br><br><b>Key Tables:</b><br>• <b>VBAK:</b> Header (Doc Type: QT)<br>• <b>VBAP:</b> Item Details<br>• <b>KONV:</b> Document Conditions<br><br><b>Dependencies:</b> Copy Control IN ➔ QT (VTAA) must be configured.<br><br><b>T-Codes:</b> VA21, VA22, VA23, VA25",
        "modal-so-title": "Sales Order (VA01) - Critical Stage",
        "modal-so-data": "<b>Concept:</b> Legal commitment. The 'Brain' of the OTC process where all major checks occur.<br><br><b>7 Critical Dependencies:</b><br>1️⃣ <b>Customer:</b> KNA1 (Gen), KNB1 (CoCode), KNVV (Sales), KNVP (Partner)<br>2️⃣ <b>Material:</b> MARA (Gen), MARC (Plant), MVKE (Sales), MARD (Stock)<br>3️⃣ <b>ATP Check:</b> Confirms qty/date (CO09, MD04). Stock - Confirmed Orders.<br>4️⃣ <b>Credit Check:</b> (OVA8) Blocked/Released in VKM1/VKM3. Checks KNKK limit.<br>5️⃣ <b>Pricing:</b> (V/08) Condition tech. Base (PR00), Tax (MWST), Cost (VPRS).<br>6️⃣ <b>Partners:</b> (VBPA) SP, SH, BP, PY determination.<br>7️⃣ <b>Incompletion:</b> (V.02) Checks mandatory fields before delivery is allowed.<br><br><b>Key Tables:</b> VBAK, VBAP, VBKD, VBPA, VBEP, KONV, VBUK, VBUP",
        "modal-del-title": "Outbound Delivery (VL01N)",
        "modal-del-data": "<b>Concept:</b> Physical preparation for shipping. Goods are picked and packed.<br><br><b>Dependencies:</b> SO must be complete & credit-released. Shipping Point determined by: Shipping Condition + Loading Group + Plant.<br><br><b>Key Tables:</b><br>• <b>LIKP:</b> Delivery Header<br>• <b>LIPS:</b> Delivery Item<br>• <b>VBFA:</b> Document Flow<br><br><b>T-Codes:</b> VL01N, VL02N, VL03N, VL06O",
        "modal-pgi-title": "Post Goods Issue (VL02N)",
        "modal-pgi-data": "<b>Concept:</b> Goods leave the warehouse. This is the primary financial posting point.<br><br><b>Automatic Actions:</b><br>1. Reduces Inventory<br>2. Creates FI Posting (Debit COGS, Credit Inventory)<br>3. Updates Delivery Status to 'Complete'<br><br><b>Key Tables:</b> MKPF (Header), MSEG (Segment), VBFA (Flow)",
        "modal-inv-title": "Billing / Invoice (VF01)",
        "modal-inv-data": "<b>Concept:</b> Requesting payment. Revenue is posted to FI.<br><br><b>FI Posting:</b> Debit Accounts Receivable, Credit Revenue, Credit Tax (10% Japan).<br><br><b>Key Tables:</b><br>• <b>VBRK:</b> Billing Header<br>• <b>VBRP:</b> Billing Item<br>• <b>BKPF / BSEG:</b> FI Accounting Records<br><br><b>T-Codes:</b> VF01, VF04, VF11, VFX3 (Release to FI)",
        "modal-pay-title": "Payment / Clearing (F-28)",
        "modal-pay-data": "<b>Concept:</b> Final step where customer payment is reconciled and AR is cleared.<br><br><b>Key Tables:</b><br>• <b>BSID:</b> Open AR Items<br>• <b>BSAD:</b> Cleared AR Items<br>• <b>BKPF / BSEG:</b> Financial Documents<br><br><b>T-Codes:</b> F-28, F-32, FBL5N (Customer Line Items)",
        
        "cs2-title": "Case Study 3: IDOC System Integration",
        "cs2-desc": "End-to-end IDOC setup from port configuration to fully automated document exchange with external systems.",
        "cs2-label-config": "⚙️ Configuration Setup — Click each step to explore",
        "cs2-n1": "Port Definition<br><span style='font-size:0.8em;opacity:0.8'>WE21</span>",
        "cs2-n2": "Partner Profile<br><span style='font-size:0.8em;opacity:0.8'>WE20</span>",
        "cs2-n3": "MSG Type Link<br><span style='font-size:0.8em;opacity:0.8'>WE57</span>",
        "cs2-n4": "Process Code<br><span style='font-size:0.8em;opacity:0.8'>WE41/42</span>",
        "cs2-n5": "Output Type<br><span style='font-size:0.8em;opacity:0.8'>NACE</span>",
        "cs2-label-inbound": "📥 Inbound IDOC Flow",
        "cs2-in-n1": "External System",
        "cs2-in-n2": "SAP Port<br><span style='opacity:0.7;font-size:0.8em'>WE21</span>",
        "cs2-in-n3": "IDOC Created<br><span style='opacity:0.7;font-size:0.8em'>Status: 50</span>",
        "cs2-in-n4": "Partner Check<br><span style='opacity:0.7;font-size:0.8em'>WE20</span>",
        "cs2-in-n5": "Process Code<br><span style='opacity:0.7;font-size:0.8em'>WE42</span>",
        "cs2-in-n6": "Function Module<br><span style='opacity:0.7;font-size:0.8em'>IDOC_INPUT_*</span>",
        "cs2-in-n7": "Sales Order ✓<br><span style='opacity:0.7;font-size:0.8em'>Status: 53</span>",
        "cs2-label-outbound": "📤 Outbound IDOC Flow",
        "cs2-out-n1": "Billing Doc<br><span style='opacity:0.7;font-size:0.8em'>VF01</span>",
        "cs2-out-n2": "NACE Output<br><span style='opacity:0.7;font-size:0.8em'>EDI1 Fires</span>",
        "cs2-out-n3": "IDOC Generated<br><span style='opacity:0.7;font-size:0.8em'>Status: 01</span>",
        "cs2-out-n4": "Port Dispatch<br><span style='opacity:0.7;font-size:0.8em'>Status: 03→12</span>",
        "cs2-out-n5": "External System<br><span style='opacity:0.7;font-size:0.8em'>Receives</span>",
        "cs2-out-n6": "ACK Received ✓<br><span style='opacity:0.7;font-size:0.8em'>Status: 16</span>",
        "cs2-btn-ref": "📊 T-Codes, Tables & Status Codes Reference",

        "modal-we21-title": "Port Definition (WE21)",
        "modal-we21-data": "<b>Purpose:</b> Defines WHERE SAP sends/receives IDOCs — the physical communication channel.<br><br><b>Configuration Example:</b><br>• <b>Port Name:</b> TAPESTRY_PORT<br>• <b>Type:</b> File Port<br>• <b>Directory:</b> /usr/sap/interfaces/tapestry/<br><br><b>Port Types Available:</b><br>• File Port — filesystem exchange<br>• RFC Port — direct SAP-to-SAP<br>• HTTP/HTTPS — web service<br><br><b>Database Table:</b> TPROT (Port definitions)",

        "modal-we20-title": "Partner Profile (WE20)",
        "modal-we20-data": "<b>Purpose:</b> Defines WHO, WHAT, and HOW for IDOC exchange.<br><br><b>Configuration Setup:</b><br>• <b>Partner No:</b> TAPESTRY_US<br>• <b>Partner Type:</b> KU (Customer)<br>• <b>Direction:</b> Inbound + Outbound<br>• <b>Message Types:</b> ORDERS, INVOIC, DESADV<br><br><b>Database Tables:</b><br>• EDIPP — Partner profile header<br>• EDIPIA — Inbound parameters<br>• EDIPOA — Outbound parameters",

        "modal-we57-title": "Message Type / IDOC Type Link (WE57)",
        "modal-we57-data": "<b>Purpose:</b> Maps Message Type → IDOC Type (defines the data structure for each document).<br><br><b>Example Mappings:</b><br>• ORDERS → ORDERS05<br>• INVOIC → INVOIC02<br>• DESADV → DESADV01<br><br><b>Related T-Codes:</b><br>• <b>WE31:</b> Create IDOC segments<br>• <b>WE30:</b> Create/display IDOC types<br>• <b>BD56:</b> ALE filter objects<br>• <b>WE57:</b> Message/IDOC assignment view",

        "modal-we42-title": "Process Code (WE41 / WE42)",
        "modal-we42-data": "<b>Purpose:</b> Maps IDOC type → SAP Function Module to trigger on receipt or send.<br><br>• <b>WE41:</b> Outbound process codes<br>• <b>WE42:</b> Inbound process codes<br><br><b>Inbound Example:</b><br>• Process Code: <b>ORDE</b><br>• Message Type: ORDERS<br>• Function Module: IDOC_INPUT_ORDERS<br>→ Automatically creates a Sales Order in SAP<br><br>⚠️ <b>Important:</b> Wrong or missing process code = Status 51 error. Always verify WE42 settings after initial config.",

        "modal-nace-title": "Output Type Configuration (NACE)",
        "modal-nace-data": "<b>Purpose:</b> Triggers automatic IDOC creation when SAP documents are saved.<br><br><b>Configuration Example:</b><br>• Output Type: <b>EDI1</b><br>• Medium: <b>6 (EDI)</b><br>• Partner Function: SP (Sold-to Party)<br><br><b>Trigger Chain:</b><br>VF01 saved → NACE fires EDI1 → IDOC Status 01 → dispatched via port → Status 12 (dispatch OK)<br><br><b>Key Point:</b> Without NACE, IDOCs must be created manually. Proper config enables full automation.",

        "modal-idoc-ref-title": "IDOC Reference: T-Codes, Tables & Status Codes",
        "modal-idoc-ref-data": "<b>Configuration T-Codes</b><br>• <b>WE20</b> — Partner Profile setup<br>• <b>WE21</b> — Port configuration<br>• <b>WE30/31</b> — IDOC types &amp; segments<br>• <b>WE57</b> — Message/IDOC type assignment<br>• <b>WE41/42</b> — Outbound/Inbound process codes<br>• <b>NACE</b> — Output type config<br>• <b>BD64</b> — ALE Distribution Model<br><br><b>Monitoring T-Codes</b><br>• <b>WE02/WE05</b> — Display/list IDOCs<br>• <b>WE09</b> — Search IDOCs by content<br>• <b>WE19</b> — Test/reprocess IDOC manually<br>• <b>BD87</b> — Reprocess failed inbound<br>• <b>WE15</b> — Reprocess failed outbound<br><br><b>Key Database Tables</b><br>• <b>EDIDC</b> — IDOC Control Records (header)<br>• <b>EDID4</b> — IDOC Data Records (content)<br>• <b>EDIDS</b> — IDOC Status Records<br>• <b>EDIPP / EDIPIA / EDIPOA</b> — Partner profile<br>• <b>TPROT</b> — Port definitions<br><br><b>Critical Status Codes</b><br>• <b>01</b> — IDOC generated<br>• <b>03</b> — Data passed to port<br>• <b>12</b> — Dispatch OK ✅<br>• <b>16</b> — Functional ACK received ✅<br>• <b style='color:#f87171'>51</b> — Error in application ⚠️ Investigate!<br>• <b style='color:#f87171'>56</b> — IDOC with errors ⚠️ Check data<br>• <b>53</b> — Successfully posted ✅ Complete",

        "cs2-quote": "At Tapestry, I monitored inbound IDOCs daily using WE02 and WE05. When IDOCs failed with status 51, I analyzed the error at segment level, checked the partner profile configuration in WE20, verified the process code in WE42, and either resolved it functionally or raised it to the ABAP team with a detailed analysis. I also used BD87 to reprocess failed IDOCs after fixes were applied.",

        "cs3-title": "Case Study 2: Global MM P2P Flow",
        "cs3-desc": "Procure-to-Pay lifecycle from internal requisition to final vendor payment, mapping critical MM technical dependencies.",
        "cs3-n1": "Purchase Req<br><span style='font-size:0.8em;opacity:0.8'>ME51N</span>",
        "cs3-n2": "RFQ<br><span style='font-size:0.8em;opacity:0.8'>ME41</span>",
        "cs3-n3": "Purchase Order<br><span style='font-size:0.8em;opacity:0.8'>ME21N</span>",
        "cs3-n4": "Goods Receipt<br><span style='font-size:0.8em;opacity:0.8'>MIGO</span>",
        "cs3-n5": "Invoice Verif<br><span style='font-size:0.8em;opacity:0.8'>MIRO</span>",
        "cs3-n6": "Payment<br><span style='font-size:0.8em;opacity:0.8'>F110</span>",
        "cs3-integ-title": "🔄 MM-SD Integration Points",
        "cs3-integ-list": "<ul style='text-align:left; padding-left:20px; list-style-type:square; font-size:0.95rem; line-height:1.6; margin-top:10px;'><li><b>ATP Check:</b> Sales Orders check MM stock levels in real-time.</li><li><b>MRP:</b> SD demand (Sales Orders) triggers PR/PO creation in MM automatically.</li><li><b>Consignment:</b> Managing vendor stock used in production (Movements 631/632).</li><li><b>Subcontracting:</b> Sending SD-demand components to vendors for processing.</li></ul>",

        "modal-p2p-pr-title": "Purchase Requisition (ME51N)",
        "modal-p2p-pr-data": "<b>Overview:</b> Internal request for materials or services. Can be manual or auto-created by MRP.<br><br><b>Key Fields:</b><br>• Account Assignment (K=Cost Center, P=Project)<br>• Doc Type: NB (Standard), ZNB (Custom)<br><br><b>Tables:</b><br>• <b>EBAN:</b> PR Header/Item data<br>• <b>EBKN:</b> PR Account Assignment",
        "modal-p2p-rfq-title": "Request for Quotation (ME41)",
        "modal-p2p-rfq-data": "<b>Overview:</b> Inviting multiple vendors to bid. Step can be skipped if vendor is pre-selected.<br><br><b>Technical Detail:</b><br>• ME49 compares vendor prices side-by-side.<br>• Rejection letters sent to losing vendors via ME41 output.<br><br><b>Tables:</b><br>• <b>EKKO/EKPO:</b> RFQ data (EBELN type 'AN')",
        "modal-p2p-po-title": "Purchase Order (ME21N) - Technical Deep Dive",
        "modal-p2p-po-data": "<b>Overview:</b> Legal contract with vendor. The core of P2P automation.<br><br><b>Critical Dependencies:</b><br>1️⃣ <b>Vendor Master:</b> LFA1 (Gen), LFB1 (Co.Code), LFM1 (Purch Org).<br>2️⃣ <b>Material Master:</b> MARA (Gen), MARC (Plant), MBEW (Valuation).<br>3️⃣ <b>Info Record:</b> (ME11) Link between Vendor + Material. Controls price & lead time.<br>4️⃣ <b>Source List:</b> (ME01) Mandatory vendor selection if MARC-PRWIS is active.<br>5️⃣ <b>Pricing Schema:</b> (V/08) Calculation of PB00 (Gross), FRA1 (Freight), etc.<br>6️⃣ <b>Release Strategy:</b> Collective release via ME28 or single via ME29N.<br><br><b>Tables:</b> EKKO (Header), EKPO (Item), EKET (Schedule), EKBE (History)",
        "modal-p2p-gr-title": "Goods Receipt (MIGO)",
        "modal-p2p-gr-data": "<b>Overview:</b> Receiving goods into the warehouse. Increases stock and triggers financial posting.<br><br><b>Movement Type 101:</b><br>• Debit: Inventory (BSX)<br>• Credit: GR/IR Clearing (WRX)<br><br><b>T-Codes:</b> MIGO (Transaction), MMBE (Stock Overview), MB51 (History)<br><br><b>Tables:</b><br>• <b>MKPF:</b> Mat. Doc Header<br>• <b>MSEG / MATDOC:</b> Mat. Doc Items",
        "modal-p2p-iv-title": "Invoice Verification (MIRO)",
        "modal-p2p-iv-data": "<b>Overview:</b> 3-Way Match (PO vs GR vs Invoice). Ensures the vendor is charged correctly.<br><br><b>Account Posting:</b><br>• Debit: GR/IR Clearing (clears the GR entry)<br>• Credit: Vendor Account (payable)<br><br><b>Blocking:</b> Invoices blocked if price/qty variance exceeds OMR6 tolerances.<br><br><b>Tables:</b> RBKPF (Header), RSEG (Item), EKBE (Update)",
        "modal-p2p-pay-title": "Payment (F110 / F-53)",
        "modal-p2p-pay-data": "<b>Overview:</b> Final clearing of vendor liability. Typically automated in large organizations.<br><br><b>F110 Process:</b><br>• Parameters ➔ Proposal ➔ Payment Run ➔ Printout.<br>• Maps payment methods (Bank, Check, Wire) to vendor bank data in LFB1.<br><br><b>Tables:</b> BSAK (Cleared), BSIK (Open Items), PAYR (Medium)",

        "section-certs": "Certifications",
        "cert-n2": "JLPT N2 (Aug 2025)",
        "cert-sd1": "SAP S/4HANA Sales Exploration (Mar 2025)",
        "cert-sd2": "SAP Certified Associate - S/4HANA Sales (Jan 2025)",
        "cert-agile": "Agile Software Development (Jun 2024)",
        "cert-uipath": "UiPath Certified RPA Associate (Feb 2023)",
        "cert-pmp": "PMP Fundamentals (Jan 2023)",
        "cert-devops": "DevOps Fundamentals (Nov 2022)",

        "section-contact": "Get in Touch",
        "contact-desc": "Ready to optimize your SAP processes in Japan? Let's connect!",
        "contact-location": "Tokyo, Japan",
        "contact-linkedin": "LinkedIn Profile",
        "contact-calendar-desc": "Want to discuss an opportunity? Book a 30-minute chat with me!",
        "btn-calendar": "🗓️ Book an Appointment",
        "resume-form-link": "https://docs.google.com/forms/d/1SickUdoDbCzDcyUc8hbXppx9hm10t_C6aPfTFRPiqFs/viewform"
    },
    ja: {
        "mascot-hero": "私の東京テーマパークへようこそ！ごゆっくりお楽しみください！",
        "mascot-about": "インドから東京に至る私のキャリアの軌跡をご覧ください！",
        "mascot-experience": "ここはビジネス街です。私のSAP経歴をご覧ください！",
        "mascot-skills": "テックアーケードへようこそ！スキルゲージがチャージされます！",
        "mascot-deeptech": "お台場エンジニアリングベイ！SAPのコアアーキテクチャを展開しています。",
        "mascot-certifications": "知識の神社です。私の資格証明書が奉納されています。",
        "mascot-contact": "スカイツリーから発信中！いつでもご連絡ください！",

        "hero-greeting": "こんにちは、",
        "hero-name": "グプタ・ディラジュ",
        "hero-title": "SAP SD バイリンガルコンサルタント",
        "hero-subtitle": "東京在住 | OTC、データ移行・導入、テスト、展開（ロールアウト）、運用サポートの専門家",
        "hero-activate": "Discover ➔ Prepare ➔ Explore ➔ Realize ➔ Deploy ➔ Run",
        "btn-english": "📄 英語レジュメ (CV)",
        "btn-rirekisho": "📝 履歴書 (Rirekisho)",
        "btn-shokumu": "💼 職務経歴書 (Details)",

        "section-about": "自己PR",
        "about-p1": "私のキャリアは、インドの製造業での購買担当からスタートしました。仕入先との価格交渉や在庫管理に従事するなかで、Zoho Inventoryの導入プロジェクトを自ら主導し、在庫回転率20%改善・保管コスト15%削減を達成しました。この経験を通じて「ITの力で業務を変える」という面白さを実感し、より大きなシステムに携わりたいという思いが強まっていきました。",
        "about-p2": "同時に、日本語を独学で本格的に学び始めました。デリー大学の東アジア研究学科でディプロマを2段階取得し、さらに日本語能力試験N2の取得に向けて毎日学習を継続しました。単に語学資格を目指すというよりも、日本のビジネス文化や仕事の進め方を深く理解し、日本企業の中で本当に役立てる人材になりたいという一心でした。",
        "about-p3": "富士通インドでは、日本のクライアントに対して日本語で直接対応する業務を担当しました。最初は専門用語や敬語表現に苦労しましたが、会議を録音して振り返り、業務マニュアルを繰り返し読み込むことで徐々に自信をつけていきました。また、UiPathを活用した調達業務の自動化にも取り組み、ITと語学を組み合わせた業務改善の手応えを感じることができました。",
        "about-p4": "キャップジェミニに入社した当初は、SAP SDの専門知識が十分ではありませんでした。しかし、ATPの設定・価格決定・出荷ポイントなど基礎から毎日自己学習を積み重ね、ベテランコンサルタントの作業を観察しながらベストプラクティスを吸収していきました。その結果、入社から半年でSD基本設定を単独担当できるレベルまで成長。1年後にはクライアントからの問い合わせに対する解決スピードが大幅に向上し、「対応が速くなった」「説明がわかりやすい」と言っていただけるようになりました。Yamaha Music・Panasonic・GC Dentalなど複数のプロジェクトを経験することで、ロールアウト・データ移行・UAT・サポートといったSAP導入の全フェーズを体験できたことは、私の最大の財産です。",
        "about-p5": "2026年3月、東京に拠点を移し、インドサクラ ジャパンに入社しました。インドでのリモート対応から、日本国内での常駐対応へと環境が変わり、より直接的に日本のクライアントと向き合う機会をいただいています。現地での実務経験を積みながら、SAP MMおよびSAP BTPの習得にも取り組んでいます。SDだけでなく、MM・BTPを横断した複合的な提案ができるコンサルタントを目指しています。私の強みは「学ぶ速さ」と「日本語と英語を使ったチームへの貢献」です。どのような環境でも、まず自分から動き、周囲と連携しながら課題を解決することを大切にしています。チームの一員として信頼されること、そしてクライアントに「この人に頼んでよかった」と思っていただけることが、私の仕事の原動力です。",

        "section-experience": "職務経歴",
        "exp-indosakura-date": "2026年3月 - 現在",
        "exp-indosakura-title": "SAP SD バイリンガルコンサルタント",
        "exp-indosakura-company": "インドサクラ ソフトウェア ジャパン | 東京",
        "exp-indosakura-b1": "OTCプロセス全体と価格決定表（Pricing Procedures）をカバーするL2/L3サポートを提供。",
        "exp-indosakura-b2": "ビジネス課題をシステム要件へ変換し、日英でのヒアリングを実施。",
        "exp-indosakura-b3": "高度な出力管理（Output Determination）および出荷ポイント設定の課題解決。",

        "exp-capgemini-date": "2023年7月 - 2026年2月",
        "exp-capgemini-title": "SAP SD バイリンガルコンサルタント",
        "exp-capgemini-company": "キャップジェミニ インド (日本市場担当)",
        "exp-capgemini-b1": "Tapestry: IDOC障害の分析とユーザーエグジット（User Exits）の設計など、インシデント解決を主導。",
        "exp-capgemini-b2": "Yamaha Music: グローバルテンプレート向けに企業構造（Enterprise Structure）とコピコントロールをマッピング。",
        "exp-capgemini-b3": "Panasonic: レガシーからS/4HANAへの大規模データ移行、およびBAPIの実装を実行。",
        "exp-capgemini-b4": "GC Dental: Panayaを利用し、E2EのOTCプロセスとRICEFW開発を含むUAT完了を支援。",

        "exp-fujitsu-date": "2022年1月 - 2023年7月",
        "exp-fujitsu-title": "テクニカルサービス担当",
        "exp-fujitsu-company": "富士通インド (日本市場担当)",
        "exp-fujitsu-b1": "グローバルパートナー向けのバイリンガル調達処理をサポート。",
        "exp-fujitsu-b2": "UiPath RPAを使用してPOおよび見積書のプロセスを自動化。",

        "exp-gupta-date": "2017年8月 - 2019年4月",
        "exp-gupta-title": "購買担当",
        "exp-gupta-company": "Gupta Industrial Hardware | インド",
        "exp-gupta-b1": "Zoho Inventoryの導入およびBPマスタの整合性調整を主導。",
        "exp-gupta-b2": "在庫回転率を20%改善し、保管コストを15%削減。",

        "section-skills": "技術力 (スキル)",
        "skill-title-sap": "SAPモジュール",
        "skill-sd": "S/4HANA SD (販売管理)",
        "skill-mm": "SAP MM (基礎)",
        "skill-btp": "SAP BTP (学習中)",
        "skill-title-integration": "統合・テスト",
        "skill-idoc": "IDOC / EDI / API連携",
        "skill-panaya": "Panaya UAT",
        "skill-rpa": "UiPath RPA",
        "skill-title-lang": "語学",
        "skill-en": "英語 (ビジネス)",
        "skill-ja": "日本語 (JLPT N2)",
        "skill-hi": "ヒンディー語 (母語)",

        "section-deeptech": "SAPプロセスと技術アーキテクチャ",
        "tech-func-title": "コア機能 (SDプロセス)",
        "tech-func-list": "<ul style='text-align:left; padding-left:20px; list-style-type:square; font-size:0.95rem; line-height:1.8; margin-top:10px;'><li>Order-to-Cash (OTC)</li><li>価格決定（Pricing）</li><li>企業構造（Enterprise Structure）</li><li>BPマスタ</li><li>出力決定（Output Determination）</li><li>コピコントロール</li><li>出荷ポイント決定</li><li>販売伝票タイプ</li><li>ATPチェック</li><li>ルート決定（Route Determination）</li><li>など</li></ul>",
        "tech-abap-title": "ABAP / 技術的専門知識",
        "tech-abap-list": "<ul style='text-align:left; padding-left:20px; list-style-type:square; font-size:0.95rem; line-height:1.8; margin-top:10px;'><li>RICEFWフレームワーク</li><li>BAPI連携</li><li>BADI実装</li><li>ユーザーエグジット（User Exits）</li><li>カスタム機能拡張</li><li>IDOC/EDIモニタリング</li></ul>",
        "tech-cloud-title": "クラウド / インテグレーション",
        "tech-cloud-list": "<ul style='text-align:left; padding-left:20px; list-style-type:square; font-size:0.95rem; line-height:1.8; margin-top:10px;'><li>SAP BTP</li><li>Integration Suite</li><li>Cloud Connector</li><li>J4C (Joule for Consultant)</li><li>J4D (Joule for Developer)</li><li>サードパーティAPI連携</li></ul>",

        "section-casestudies": "アーキテクチャ事例 (Case Studies)",
        "cs1-title": "事例 1：グローバル E2E OTCフロー",
        "cs1-desc": "引き合いから最終入金までをマッピング。SAP SDの高度な技術アーキテクチャを示します。",
        "cs1-n1": "引き合い<br><span style='font-size:0.8em;opacity:0.8'>VA11</span>",
        "cs1-n2": "見積<br><span style='font-size:0.8em;opacity:0.8'>VA21</span>",
        "cs1-n3": "受注<br><span style='font-size:0.8em;opacity:0.8'>VA01</span>",
        "cs1-n4": "出荷伝票<br><span style='font-size:0.8em;opacity:0.8'>VL01N</span>",
        "cs1-n5": "出庫転記<br><span style='font-size:0.8em;opacity:0.8'>VL02N</span>",
        "cs1-n6": "請求伝票<br><span style='font-size:0.8em;opacity:0.8'>VF01</span>",
        "cs1-n7": "入金/消込<br><span style='font-size:0.8em;opacity:0.8'>F-28</span>",

        "modal-inq-title": "引き合い / 照会 (VA11)",
        "modal-inq-data": "<b>概要:</b> 情報収集フェーズ。顧客が価格や在庫状況を確認しますが、法的義務は発生しません。<br><br><b>主要テーブル:</b><br>• <b>VBAK:</b> ヘッダ (伝票タイプ: IN)<br>• <b>VBAP:</b> 明細データ<br>• <b>VBKD:</b> ビジネスデータ (支払条件)<br><br><b>Tコード:</b> VA11, VA12, VA13, VA15",
        "modal-qt-title": "見積 (VA21)",
        "modal-qt-data": "<b>概要:</b> 法的束縛力のあるオファー。価格と有効期限が固定され、販売側に履行義務が生じます。<br><br><b>主要テーブル:</b><br>• <b>VBAK:</b> ヘッダ (伝票タイプ: QT)<br>• <b>VBAP:</b> 明細詳細<br>• <b>KONV:</b> 伝票条件 (価格決定)<br><br><b>依存関係:</b> コピー管理 IN ➔ QT (VTAA) の設定が必須です。<br><br><b>Tコード:</b> VA21, VA22, VA23, VA25",
        "modal-so-title": "受注 (VA01) - 最重要フェーズ",
        "modal-so-data": "<b>概要:</b> 法的契約。OTCプロセスの「脳」であり、すべての主要なチェックがここで実行されます。<br><br><b>7つの重要な依存関係:</b><br>1️⃣ <b>得先マスタ:</b> KNA1 (一般), KNB1 (会社), KNVV (販売), KNVP (取引先)<br>2️⃣ <b>品目マスタ:</b> MARA (一般), MARC (プラント), MVKE (販売), MARD (在庫)<br>3️⃣ <b>ATPチェック:</b> 在庫確認 (CO09, MD04)。在庫 - 確認済受注量。<br>4️⃣ <b>与信チェック:</b> (OVA8) VKM1/VKM3でブロック/解除。KNKK限度額を確認。<br>5️⃣ <b>価格決定:</b> (V/08) 条件技法。基本価格(PR00), 税(MWST), 原価(VPRS)。<br>6️⃣ <b>取引先機能:</b> (VBPA) 受注先、出荷先、請求先、支払人の決定。<br>7️⃣ <b>不完全ログ:</b> (V.02) 出荷前に必須項目の入力を検証。<br><br><b>主要テーブル:</b> VBAK, VBAP, VBKD, VBPA, VBEP, KONV, VBUK, VBUP",
        "modal-del-title": "出荷伝票 (VL01N)",
        "modal-del-data": "<b>概要:</b> 配送に向けた物理的準備。ピッキングと梱包が含まれます。<br><br><b>依存関係:</b> 受注が完了し、与信ブロックが解除されている必要があります。出荷ポイント決定: 出荷条件 + 荷役グループ + プラント。<br><br><b>主要テーブル:</b><br>• <b>LIKP:</b> 出荷ヘッダ<br>• <b>LIPS:</b> 出荷明細<br>• <b>VBFA:</b> 伝票フロー<br><br><b>Tコード:</b> VL01N, VL02N, VL03N, VL06O",
        "modal-pgi-title": "出庫転記 (VL02N)",
        "modal-pgi-data": "<b>概要:</b> 商品が倉庫を出発。財務会計上の最も重要な転記ポイントです。<br><br><b>自動実行アクション:</b><br>1. 在庫の減少<br>2. 会計伝票の作成 (借方: 売上原価, 貸方: 棚卸資産)<br>3. 出荷ステータスを「完了」に更新<br><br><b>主要テーブル:</b> MKPF (ヘッダ), MSEG (セグメント), VBFA (フロー)",
        "modal-inv-title": "請求 / インボイス (VF01)",
        "modal-inv-data": "<b>概要:</b> 支払い請求。収益がFI（財務会計）に転記されます。<br><br><b>FI転記:</b> 借方 売掛金, 貸方 収益, 貸方 消費税 (日本 10%)。<br><br><b>主要テーブル:</b><br>• <b>VBRK:</b> 請求ヘッダ<br>• <b>VBRP:</b> 請求明細<br>• <b>BKPF / BSEG:</b> 会計伝票詳細<br><br><b>Tコード:</b> VF01, VF04, VF11, VFX3 (FIへの承認放出)",
        "modal-pay-title": "入金 / 消込 (F-28)",
        "modal-pay-data": "<b>概要:</b> 最終ステップ。顧客からの入金を照合し、売掛金を消し込みます。<br><br><b>主要テーブル:</b><br>• <b>BSID:</b> 未消込債権明細<br>• <b>BSAD:</b> 消込済債権明細<br>• <b>BKPF / BSEG:</b> 財務会計伝票<br><br><b>Tコード:</b> F-28, F-32, FBL5N (得意先明細表示)",

        "cs2-title": "事例 3：IDOCによるシステム統合",
        "cs2-desc": "ポート設定から外部システムとの完全自動伝票交換まで、エンドツーエンドのIDOCセットアップ。",
        "cs2-label-config": "⚙️ 設定セットアップ — 各ステップをクリックして詳細を表示",
        "cs2-n1": "ポート定義<br><span style='font-size:0.8em;opacity:0.8'>WE21</span>",
        "cs2-n2": "パートナープロファイル<br><span style='font-size:0.8em;opacity:0.8'>WE20</span>",
        "cs2-n3": "メッセージタイプリンク<br><span style='font-size:0.8em;opacity:0.8'>WE57</span>",
        "cs2-n4": "プロセスコード<br><span style='font-size:0.8em;opacity:0.8'>WE41/42</span>",
        "cs2-n5": "出力タイプ<br><span style='font-size:0.8em;opacity:0.8'>NACE</span>",
        "cs2-label-inbound": "📥 受信IDOCフロー",
        "cs2-in-n1": "外部システム",
        "cs2-in-n2": "SAPポート<br><span style='opacity:0.7;font-size:0.8em'>WE21</span>",
        "cs2-in-n3": "IDOC生成<br><span style='opacity:0.7;font-size:0.8em'>ステータス: 50</span>",
        "cs2-in-n4": "パートナーチェック<br><span style='opacity:0.7;font-size:0.8em'>WE20</span>",
        "cs2-in-n5": "プロセスコード<br><span style='opacity:0.7;font-size:0.8em'>WE42</span>",
        "cs2-in-n6": "機能モジュール<br><span style='opacity:0.7;font-size:0.8em'>IDOC_INPUT_*</span>",
        "cs2-in-n7": "受注作成 ✓<br><span style='opacity:0.7;font-size:0.8em'>ステータス: 53</span>",
        "cs2-label-outbound": "📤 送信IDOCフロー",
        "cs2-out-n1": "請求伝票<br><span style='opacity:0.7;font-size:0.8em'>VF01</span>",
        "cs2-out-n2": "NACE出力<br><span style='opacity:0.7;font-size:0.8em'>EDI1起動</span>",
        "cs2-out-n3": "IDOC生成<br><span style='opacity:0.7;font-size:0.8em'>ステータス: 01</span>",
        "cs2-out-n4": "ポート送信<br><span style='opacity:0.7;font-size:0.8em'>ステータス: 03→12</span>",
        "cs2-out-n5": "外部システム<br><span style='opacity:0.7;font-size:0.8em'>受信完了</span>",
        "cs2-out-n6": "ACK受信 ✓<br><span style='opacity:0.7;font-size:0.8em'>ステータス: 16</span>",
        "cs2-btn-ref": "📊 Tコード、テーブル、ステータスコードのリファレンス",

        "modal-we21-title": "ポート定義 (WE21)",
        "modal-we21-data": "<b>目的:</b> IDOCの送受信先（物理的な通信チャネル）を定義します。<br><br><b>設定例:</b><br>• <b>ポート名:</b> TAPESTRY_PORT<br>• <b>タイプ:</b> ファイルポート<br>• <b>ディレクトリ:</b> /usr/sap/interfaces/tapestry/<br><br><b>利用可能なポートタイプ:</b><br>• ファイルポート — ファイルシステム経由<br>• RFCポート — SAP間直接接続<br>• HTTP/HTTPS — Webサービス<br><br><b>データベーステーブル:</b> TPROT",

        "modal-we20-title": "パートナープロファイル (WE20)",
        "modal-we20-data": "<b>目的:</b> IDOC交換の相手先・内容・方法を定義します。<br><br><b>設定:</b><br>• <b>パートナー番号:</b> TAPESTRY_US<br>• <b>パートナータイプ:</b> KU（得意先）<br>• <b>方向:</b> 受信 + 送信<br>• <b>メッセージタイプ:</b> ORDERS, INVOIC, DESADV<br><br><b>データベーステーブル:</b><br>• EDIPP — パートナープロファイルヘッダ<br>• EDIPIA — 受信パラメータ<br>• EDIPOA — 送信パラメータ",

        "modal-we57-title": "メッセージタイプ / IDOCタイプリンク (WE57)",
        "modal-we57-data": "<b>目的:</b> メッセージタイプ → IDOCタイプのマッピング（各伝票のデータ構造定義）。<br><br><b>マッピング例:</b><br>• ORDERS → ORDERS05<br>• INVOIC → INVOIC02<br>• DESADV → DESADV01<br><br><b>関連Tコード:</b><br>• <b>WE31:</b> IDOCセグメント作成<br>• <b>WE30:</b> IDOCタイプ表示/作成<br>• <b>BD56:</b> ALEフィルタオブジェクト",

        "modal-we42-title": "プロセスコード (WE41 / WE42)",
        "modal-we42-data": "<b>目的:</b> IDOCタイプ → 実行するSAP機能モジュールのマッピング。<br><br>• <b>WE41:</b> 送信プロセスコード<br>• <b>WE42:</b> 受信プロセスコード<br><br><b>受信例:</b><br>• プロセスコード: <b>ORDE</b><br>• メッセージタイプ: ORDERS<br>• 機能モジュール: IDOC_INPUT_ORDERS<br>→ 受注を自動的に作成<br><br>⚠️ <b>重要:</b> プロセスコードが誤っている場合、ステータス51エラーが発生します。",

        "modal-nace-title": "出力タイプ設定 (NACE)",
        "modal-nace-data": "<b>目的:</b> SAP伝票保存時にIDOC自動生成をトリガーします。<br><br><b>設定:</b><br>• 出力タイプ: <b>EDI1</b><br>• 媒体: <b>6（EDI）</b><br>• 相手先機能: SP（受注先）<br><br><b>トリガーチェーン:</b><br>VF01保存 → NACE EDI1起動 → IDOC ステータス01 → ポート経由送信 → ステータス12<br><br><b>ポイント:</b> NACE設定なしでは手動でIDOCを作成する必要があります。",

        "modal-idoc-ref-title": "IDOCリファレンス: Tコード・テーブル・ステータスコード",
        "modal-idoc-ref-data": "<b>設定Tコード</b><br>• <b>WE20</b> — パートナープロファイル<br>• <b>WE21</b> — ポート設定<br>• <b>WE30/31</b> — IDOCタイプ/セグメント<br>• <b>WE57</b> — MSG/IDOCタイプ割当<br>• <b>WE41/42</b> — 送受信プロセスコード<br>• <b>NACE</b> — 出力タイプ設定<br>• <b>BD64</b> — ALEディストリビューションモデル<br><br><b>監視Tコード</b><br>• <b>WE02/WE05</b> — IDOC表示/一覧<br>• <b>WE09</b> — コンテンツ検索<br>• <b>WE19</b> — テスト/再処理<br>• <b>BD87</b> — 受信失敗IDOCの再処理<br>• <b>WE15</b> — 送信失敗IDOCの再処理<br><br><b>主要データベーステーブル</b><br>• <b>EDIDC</b> — IDOCコントロールレコード（ヘッダ）<br>• <b>EDID4</b> — IDOCデータレコード（内容）<br>• <b>EDIDS</b> — IDOCステータスレコード<br>• <b>EDIPP/EDIPIA/EDIPOA</b> — パートナープロファイル<br>• <b>TPROT</b> — ポート定義<br><br><b>重要ステータスコード</b><br>• <b>01</b> — IDOC生成済<br>• <b>12</b> — 送信OK ✅<br>• <b>16</b> — 機能確認応答受信 ✅<br>• <b style='color:#f87171'>51</b> — アプリケーションエラー ⚠️<br>• <b style='color:#f87171'>56</b> — エラーあり ⚠️<br>• <b>53</b> — 正常転記 ✅",

        "cs2-quote": "Tapestryでは、WE02とWE05を使用して毎日受信IDOCを監視していました。IDOCがステータス51で失敗した場合、セグメントレベルでエラーを分析し、WE20でパートナープロファイル設定を確認、WE42でプロセスコードを検証し、機能的に解決するかABAPチームに詳細な分析を共有して対応を依頼しました。修正適用後はBD87を使用して失敗したIDOCを再処理しました。",

        "cs3-title": "事例 2：グローバル MM P2Pフロー",
        "cs3-desc": "購入依頼から最終的なベンダー支払いまでのライフサイクル。SAP MMの高度な技術적依存関係をマッピング。",
        "cs3-n1": "購入依頼<br><span style='font-size:0.8em;opacity:0.8'>ME51N</span>",
        "cs3-n2": "見積依頼 (RFQ)<br><span style='font-size:0.8em;opacity:0.8'>ME41</span>",
        "cs3-n3": "購買発注 (PO)<br><span style='font-size:0.8em;opacity:0.8'>ME21N</span>",
        "cs3-n4": "入庫 (GR)<br><span style='font-size:0.8em;opacity:0.8'>MIGO</span>",
        "cs3-n5": "請求書照合 (IV)<br><span style='font-size:0.8em;opacity:0.8'>MIRO</span>",
        "cs3-n6": "支払実行<br><span style='font-size:0.8em;opacity:0.8'>F110</span>",
        "cs3-integ-title": "🔄 MM-SD 統合ポイント",
        "cs3-integ-list": "<ul style='text-align:left; padding-left:20px; list-style-type:square; font-size:0.95rem; line-height:1.6; margin-top:10px;'><li><b>ATPチェック:</b> 受注登録時にMMの在庫レベルをリアルタイムで確認。</li><li><b>MRP:</b> SDの需要（受注）に基づいて、MMでPR/POを自動生成。</li><li><b>預託在庫:</b> 製造で使用するベンダー在庫の管理（移動タイプ 631/632）。</li><li><b>外注加工:</b> SD需要に基づいた構成品をベンダーに送付し加工を依頼。</li></ul>",

        "modal-p2p-pr-title": "購入依頼 (ME51N)",
        "modal-p2p-pr-data": "<b>概要:</b> 材料やサービスの内部要求。手動またはMRPによって自動登録されます。<br><br><b>主要項目:</b><br>• 勘定設定 (K=原価中心点, P=プロジェクト)<br>• 伝票タイプ: NB (標準), ZNB (カスタム)<br><br><b>主要テーブル:</b><br>• <b>EBAN:</b> 購入依頼ヘッダ/明細データ<br>• <b>EBKN:</b> 購入依頼勘定設定",
        "modal-p2p-rfq-title": "見積依頼 / RFQ (ME41)",
        "modal-p2p-rfq-data": "<b>概要:</b> 複数のベンダーへの価格見積依頼。ベンダーが既知の場合は省略可能です。<br><br><b>技術的詳細:</b><br>• ME49で各ベンダーの見積価格を並べて比較。<br>• 不採用のベンダーにはME41の出力機能で拒絶通知を送信。<br><br><b>主要テーブル:</b><br>• <b>EKKO/EKPO:</b> RFQデータ (伝票タイプ 'AN')",
        "modal-p2p-po-title": "購買発注 (ME21N) - 技術的ディープダイブ",
        "modal-p2p-po-data": "<b>概要:</b> ベンダーとの法的契約。P2P自動化の中核です。<br><br><b>重要な依存関係:</b><br>1️⃣ <b>仕入先マスタ:</b> LFA1 (一般), LFB1 (会社), LFM1 (購買組織)。<br>2️⃣ <b>品目マスタ:</b> MARA (一般), MARC (プラント), MBEW (評価)。<br>3️⃣ <b>購買情報 (Info Record):</b> (ME11) 仕入先+品目のリンク。価格とリードタイムを制御。<br>4️⃣ <b>供給元一覧:</b> (ME01) MARC-PRWISが有効な場合、必須の仕入先選択。<br>5️⃣ <b>価格決定手続:</b> (V/08) PB00 (グロス価格)、FRA1 (運賃) 等の計算ロジック。<br>6️⃣ <b>承認戦略:</b> ME28（一括承認）またはME29N（個別承認）。<br><br><b>主要テーブル:</b> EKKO (ヘッダ), EKPO (明細), EKET (納入日程), EKBE (履歴)",
        "modal-p2p-gr-title": "入庫 (MIGO)",
        "modal-p2p-gr-data": "<b>概要:</b> 倉庫への商品の受け取り。在庫を増やし、会計転記をトリガーします。<br><br><b>移動タイプ 101:</b><br>• 借方: 在庫 (BSX)<br>• 貸方: 入庫/請求仮勘定 (WRX)<br><br><b>Tコード:</b> MIGO (トランザクション), MMBE (在庫概要), MB51 (履歴)<br><br><b>主要テーブル:</b><br>• <b>MKPF:</b> 入出庫伝票ヘッダ<br>• <b>MSEG / MATDOC:</b> 入出庫伝票明細",
        "modal-p2p-iv-title": "請求書照合 (MIRO)",
        "modal-p2p-iv-data": "<b>概要:</b> 3点照会 (PO vs GR vs 請求書)。ベンダーへの支払額が正しいことを検証します。<br><br><b>会計転記:</b><br>• 借方: 入庫/請求仮勘定 (GR時の仮勘定をクリア)<br>• 貸方: ベンダー勘定 (未払金ポスト)<br><br><b>ブロック機能:</b> 価格/数量の差異がOMR6の許容範囲を超えると請求書が支払保留されます。<br><br><b>主要テーブル:</b> RBKPF (ヘッダ), RSEG (明細), EKBE (履歴更新)",
        "modal-p2p-pay-title": "支払実行 (F110 / F-53)",
        "modal-p2p-pay-data": "<b>概要:</b> ベンダー債務の最終決済。大企業では通常、自動支払プログラムが使用されます。<br><br><b>F110 プロセス:</b><br>• パラメータ設定 ➔ 提案 ➔ 支払実行 ➔ 印刷/DME送信。<br>• 支払方法（銀行振込、小切手等）をベンダーマスタの銀行データと照合。<br><br><b>主要テーブル:</b> BSAK (消込済), BSIK (未消込), PAYR (支払媒体データ)",

        "section-certs": "資格・認定",
        "cert-n2": "日本語能力試験 N2 (2025年8月)",
        "cert-sd1": "SAP S/4HANA Sales Exploration (2025年3月)",
        "cert-sd2": "SAP Certified Associate - S/4HANA Sales (2025年1月)",
        "cert-agile": "Agile Software Development (2024年6月)",
        "cert-uipath": "UiPath Certified RPA Associate (2023年2月)",
        "cert-pmp": "PMP Fundamentals (2023年1月)",
        "cert-devops": "DevOps Fundamentals (2022年11月)",

        "section-contact": "お問い合わせ",
        "contact-desc": "日本でのSAPプロセス最適化にご興味はありますか？ぜひご連絡ください！",
        "contact-location": "日本、東京",
        "contact-linkedin": "LinkedIn プロフィール",
        "contact-calendar-desc": "プロジェクトのご相談はありませんか？30分のカジュアル面談を予約する：",
        "btn-calendar": "🗓️ 面談を予約する",
        "resume-form-link": "https://docs.google.com/forms/d/1SickUdoDbCzDcyUc8hbXppx9hm10t_C6aPfTFRPiqFs/viewform"
    }
};
