const translations = {
    en: {
        "mascot-hero": "Welcome to my Tokyo Theme Park! Enjoy the tour!",
        "mascot-experience": "This is the business district. Look at my SAP projects!",
        "mascot-skills": "Welcome to the Tech Arcade! Watch my skill bars power up!",
        "mascot-deeptech": "The Odaiba Engineering Bay! Core SAP architecture lies here.",
        "mascot-certifications": "The Shrine of Knowledge. My top certifications are kept here.",
        "mascot-contact": "Broadcasting from the Skytree! Drop me an email!",
        
        "hero-greeting": "Hi, I'm",
        "hero-name": "Dheeraj Gupta",
        "hero-title": "SAP SD Bilingual Consultant",
        "hero-subtitle": "Based in Tokyo | Expert in OTC, Data Migration & Support",
        
        "section-experience": "Experience Timeline",
        "exp-indosakura-date": "Mar 2026 - Present",
        "exp-indosakura-title": "SAP SD Bilingual Consultant",
        "exp-indosakura-company": "IndoSakura Software Japan | Tokyo",
        "exp-indosakura-b1": "Providing L2/L3 support covering core OTC processes and Pricing Procedures.",
        "exp-indosakura-b2": "Gathering bilingual requirements to map business needs into System Architecture.",
        "exp-indosakura-b3": "Resolving advanced output determination and shipping point issues.",

        "exp-capgemini-date": "Jul 2023 - Feb 2026",
        "exp-capgemini-title": "SAP SD Bilingual Consultant",
        "exp-capgemini-company": "Capgemini India (Japan Market)",
        "exp-capgemini-b1": "Tapestry: Handled production support, analyzing IDOC failures and designing User Exits.",
        "exp-capgemini-b2": "Yamaha Music: Mapped Enterprise Structure and customized Copy Control for Global Templates.",
        "exp-capgemini-b3": "Panasonic: Executed complex Legacy-to-S/4HANA Data Migrations and implemented BAPIs.",
        "exp-capgemini-b4": "GC Dental: Led Panaya UAT test cycles covering end-to-end OTC and custom RICEFW enhancements.",

        "exp-fujitsu-date": "Jan 2022 - Jul 2023",
        "exp-fujitsu-title": "Technical Service Representative",
        "exp-fujitsu-company": "Fujitsu India (Japan Market)",
        "exp-fujitsu-b1": "Supported bilingual procurement processing for global partners.",
        "exp-fujitsu-b2": "Automated PO and Quote processes using UiPath RPA.",

        "exp-gupta-date": "Aug 2017 - Apr 2019",
        "exp-gupta-title": "Procurement Executive",
        "exp-gupta-company": "Gupta Industrial Hardware | India",
        "exp-gupta-b1": "Led Zoho Inventory implementation and BP Master alignment.",
        "exp-gupta-b2": "Improved inventory turnover by 20% and slashed costs by 15%.",

        "section-skills": "Tech Arsenal",
        "skill-title-sap": "SAP Modules",
        "skill-sd": "S/4HANA SD (Sales)",
        "skill-mm": "SAP MM (Basics)",
        "skill-btp": "SAP BTP (Learning)",
        "skill-title-integration": "Integration & Testing",
        "skill-idoc": "IDOC / EDI / API",
        "skill-panaya": "Panaya UAT",
        "skill-rpa": "UiPath RPA",
        "skill-title-lang": "Languages",
        "skill-en": "English (Business)",
        "skill-ja": "Japanese (JLPT N2)",
        "skill-hi": "Hindi (Native)",

        "section-deeptech": "SAP Architecture & Processes",
        "tech-func-title": "Core Functional (SD)",
        "tech-func-list": "Order-to-Cash (OTC) • Pricing Procedures • Enterprise Structure • BP Master • Output Determination • Copy Control • Shipping Point Determination • Sales Document Types",
        "tech-abap-title": "Technical & ABAP",
        "tech-abap-list": "RICEFW Framework • BAPI Integration • BADI Implementations • User Exits • Custom Enhancements • IDOC/EDI Monitoring",
        "tech-cloud-title": "Cloud & Integration",
        "tech-cloud-list": "SAP BTP • Integration Suite • Cloud Connector • Java Connector (JCo / J4C) • Third-Party API Sync",

        "section-certs": "Certifications",
        "cert-n2": "JLPT N2 (Aug 2025)",
        "cert-sd1": "SAP S/4HANA Sales Exploration (Mar 2025)",
        "cert-sd2": "SAP Certified Associate - S/4HANA Sales (Jan 2025)",
        "cert-agile": "Agile Software Development (Jun 2024)",
        "cert-uipath": "UiPath Certified RPA Associate (Feb 2023)",
        "cert-pmp": "PMP Fundamentals (Jan 2023)",
        "cert-devops": "DevOps Fundamentals (Nov 2022)",

        "section-contact": "Get in Touch",
        "contact-desc": "Ready to optimize your SAP processes in Japan? Let's connect!",
        "contact-location": "Tokyo, Japan",
        "contact-linkedin": "LinkedIn Profile"
    },
    ja: {
        "mascot-hero": "私の東京テーマパークへようこそ！ごゆっくりお楽しみください！",
        "mascot-experience": "ここはビジネス街です。私のSAP経歴をご覧ください！",
        "mascot-skills": "テックアーケードへようこそ！スキルゲージがチャージされます！",
        "mascot-deeptech": "お台場エンジニアリングベイ！SAPのコアアーキテクチャを展開しています。",
        "mascot-certifications": "知識の神社です。私の資格証明書が奉納されています。",
        "mascot-contact": "スカイツリーから発信中！いつでもご連絡ください！",

        "hero-greeting": "こんにちは、",
        "hero-name": "グプタ・ディラジュです",
        "hero-title": "SAP SD バイリンガルコンサルタント",
        "hero-subtitle": "東京在住 | OTC、データ移行、運用サポートの専門家",

        "section-experience": "職務経歴",
        "exp-indosakura-date": "2026年3月 - 現在",
        "exp-indosakura-title": "SAP SD バイリンガルコンサルタント",
        "exp-indosakura-company": "インドサクラ ソフトウェア ジャパン | 東京",
        "exp-indosakura-b1": "OTCプロセス全体と価格決定表（Pricing Procedures）をカバーするL2/L3サポートを提供。",
        "exp-indosakura-b2": "ビジネス課題をシステム要件へ変換し、日英でのヒアリングを実施。",
        "exp-indosakura-b3": "高度な出力管理（Output Determination）および出荷ポイント設定の課題解決。",

        "exp-capgemini-date": "2023年7月 - 2026年2月",
        "exp-capgemini-title": "SAP SD バイリンガルコンサルタント",
        "exp-capgemini-company": "キャップジェミニ インド (日本市場担当)",
        "exp-capgemini-b1": "Tapestry: IDOC障害の分析とユーザーエグジット（User Exits）の設計など、インシデント解決を主導。",
        "exp-capgemini-b2": "Yamaha Music: グローバルテンプレート向けに企業構造（Enterprise Structure）とコピコントロールをマッピング。",
        "exp-capgemini-b3": "Panasonic: レガシーからS/4HANAへの大規模データ移行、およびBAPIの実装を実行。",
        "exp-capgemini-b4": "GC Dental: Panayaを利用し、E2EのOTCプロセスとRICEFW開発を含むUAT完了を支援。",

        "exp-fujitsu-date": "2022年1月 - 2023年7月",
        "exp-fujitsu-title": "テクニカルサービス担当",
        "exp-fujitsu-company": "富士通インド (日本市場担当)",
        "exp-fujitsu-b1": "グローバルパートナー向けのバイリンガル調達処理をサポート。",
        "exp-fujitsu-b2": "UiPath RPAを使用してPOおよび見積書のプロセスを自動化。",

        "exp-gupta-date": "2017年8月 - 2019年4月",
        "exp-gupta-title": "購買担当",
        "exp-gupta-company": "Gupta Industrial Hardware | インド",
        "exp-gupta-b1": "Zoho Inventoryの導入およびBPマスタの整合性調整を主導。",
        "exp-gupta-b2": "在庫回転率を20%改善し、保管コストを15%削減。",

        "section-skills": "技術力 (スキル)",
        "skill-title-sap": "SAPモジュール",
        "skill-sd": "S/4HANA SD (販売管理)",
        "skill-mm": "SAP MM (基礎)",
        "skill-btp": "SAP BTP (学習中)",
        "skill-title-integration": "統合・テスト",
        "skill-idoc": "IDOC / EDI / API連携",
        "skill-panaya": "Panaya UAT",
        "skill-rpa": "UiPath RPA",
        "skill-title-lang": "語学",
        "skill-en": "英語 (ビジネス)",
        "skill-ja": "日本語 (JLPT N2)",
        "skill-hi": "ヒンディー語 (母語)",

        "section-deeptech": "SAPプロセスと技術アーキテクチャ",
        "tech-func-title": "コア機能 (SDプロセス)",
        "tech-func-list": "Order-to-Cash (OTC) • 価格決定（Pricing） • 企業構造（Enterprise Structure） • BPマスタ • 出力決定（Output Determination） • コピコントロール • 出荷ポイント決定 • 販売伝票タイプ",
        "tech-abap-title": "ABAP / 技術的専門知識",
        "tech-abap-list": "RICEFWフレームワーク • BAPI連携 • BADI実装 • ユーザーエグジット（User Exits） • カスタム機能拡張 • IDOC/EDIモニタリング",
        "tech-cloud-title": "クラウド / インテグレーション",
        "tech-cloud-list": "SAP BTP • Integration Suite • Cloud Connector • Java Connector (JCo / J4C) • サードパーティAPI連携",

        "section-certs": "資格・認定",
        "cert-n2": "日本語能力試験 N2 (2025年8月)",
        "cert-sd1": "SAP S/4HANA Sales Exploration (2025年3月)",
        "cert-sd2": "SAP Certified Associate - S/4HANA Sales (2025年1月)",
        "cert-agile": "Agile Software Development (2024年6月)",
        "cert-uipath": "UiPath Certified RPA Associate (2023年2月)",
        "cert-pmp": "PMP Fundamentals (2023年1月)",
        "cert-devops": "DevOps Fundamentals (2022年11月)",

        "section-contact": "お問い合わせ",
        "contact-desc": "日本でのSAPプロセス最適化にご興味はありますか？ぜひご連絡ください！",
        "contact-location": "日本、東京",
        "contact-linkedin": "LinkedIn プロフィール"
    }
};
