const translations = {
    en: {
        "mascot-hero": "Welcome to my Tokyo Theme Park! Enjoy the tour!",
        "mascot-about": "Learn more about my journey from India to SAP consulting in Tokyo!",
        "mascot-experience": "This is the business district. Look at my SAP projects!",
        "mascot-skills": "Welcome to the Tech Arcade! Watch my skill bars power up!",
        "mascot-deeptech": "The Odaiba Engineering Bay! Core SAP architecture lies here.",
        "mascot-certifications": "The Shrine of Knowledge. My top certifications are kept here.",
        "mascot-contact": "Broadcasting from the Skytree! Drop me an email!",
        
        "hero-greeting": "Hi, I'm",
        "hero-name": "Dheeraj Gupta",
        "hero-title": "SAP SD Bilingual Consultant",
        "hero-subtitle": "Based in Tokyo | Expert in OTC, Data Migration and Implementation, Testing, Rollout and Support",
        "hero-activate": "Discover ➔ Prepare ➔ Explore ➔ Realize ➔ Deploy ➔ Run",
        "btn-english": "📄 English CV",
        "btn-rirekisho": "📝 履歴書 (Rirekisho)",
        "btn-shokumu": "💼 職務経歴書 (Details)",
        
        "section-about": "Self PR / My Journey",
        "about-p1": "My career started in procurement in the Indian manufacturing industry, where I spearheaded the implementation of Zoho Inventory, improving inventory turnover by 20% and reducing storage costs by 15%. This experience sparked my passion for using IT to drive business transformation, motivating me to pivot toward larger ERP systems.",
        "about-p2": "Simultaneously, I dedicated myself to mastering the Japanese language. I earned two diplomas from Delhi University's Department of East Asian Studies and passed the JLPT N2. My goal wasn't just acquiring language certifications, but deeply understanding Japanese business culture to become a valuable asset within Japanese organizations.",
        "about-p3": "At Fujitsu India, I directly supported Japanese clients. Initially challenged by technical jargon and Keigo, I overcame this by recording meetings for review and thoroughly memorizing manuals. I also successfully automated procurement workflows using UiPath RPA, cementing my belief in combining language capabilities with IT.",
        "about-p4": "Upon joining Capgemini, I immersed myself in SAP SD, self-studying foundational concepts like ATP, Pricing, and Shipping Points daily. Within six months, I was independently handling core SD configurations, and within a year, my accelerated resolution speed earned high client praise. Gaining hands-on experience across the entire SAP implementation lifecycle—Rollouts, Data Migrations, UAT, and Support—on major projects like Yamaha Music, Panasonic, and GC Dental remains my greatest professional asset.",
        "about-p5": "In March 2026, I relocated to Tokyo and joined IndoSakura Software Japan. Transitioning from remote support to an on-site environment has given me the opportunity to engage directly with local clients. As I continue to grow, I am actively learning SAP MM and SAP BTP to evolve into a multi-dimensional consultant capable of proposing comprehensive, cross-module solutions. My greatest strengths are my 'speed of learning' and 'bilingual team contribution'. I am driven by the desire to earn my team's trust and consistently deliver results.",

        "section-experience": "Experience Timeline",
        "exp-indosakura-date": "Mar 2026 - Present",
        "exp-indosakura-title": "SAP SD Bilingual Consultant",
        "exp-indosakura-company": "IndoSakura Software Japan | Tokyo",
        "exp-indosakura-b1": "Providing L2/L3 support covering core OTC processes and Pricing Procedures.",
        "exp-indosakura-b2": "Gathering bilingual requirements to map business needs into System Architecture.",
        "exp-indosakura-b3": "Resolving advanced output determination and shipping point issues.",

        "exp-capgemini-date": "Jul 2023 - Feb 2026",
        "exp-capgemini-title": "SAP SD Bilingual Consultant",
        "exp-capgemini-company": "Capgemini India (Japan Market)",
        "exp-capgemini-b1": "Tapestry: Handled production support, analyzing IDOC failures and designing User Exits.",
        "exp-capgemini-b2": "Yamaha Music: Mapped Enterprise Structure and customized Copy Control for Global Templates.",
        "exp-capgemini-b3": "Panasonic: Executed complex Legacy-to-S/4HANA Data Migrations and implemented BAPIs.",
        "exp-capgemini-b4": "GC Dental: Led Panaya UAT test cycles covering end-to-end OTC and custom RICEFW enhancements.",

        "exp-fujitsu-date": "Jan 2022 - Jul 2023",
        "exp-fujitsu-title": "Technical Service Representative",
        "exp-fujitsu-company": "Fujitsu India (Japan Market)",
        "exp-fujitsu-b1": "Supported bilingual procurement processing for global partners.",
        "exp-fujitsu-b2": "Automated PO and Quote processes using UiPath RPA.",

        "exp-gupta-date": "Aug 2017 - Apr 2019",
        "exp-gupta-title": "Procurement Executive",
        "exp-gupta-company": "Gupta Industrial Hardware | India",
        "exp-gupta-b1": "Led Zoho Inventory implementation and BP Master alignment.",
        "exp-gupta-b2": "Improved inventory turnover by 20% and slashed costs by 15%.",

        "section-skills": "Tech Arsenal",
        "skill-title-sap": "SAP Modules",
        "skill-sd": "S/4HANA SD (Sales)",
        "skill-mm": "SAP MM (Basics)",
        "skill-btp": "SAP BTP (Learning)",
        "skill-title-integration": "Integration & Testing",
        "skill-idoc": "IDOC / EDI / API",
        "skill-panaya": "Panaya UAT",
        "skill-rpa": "UiPath RPA",
        "skill-title-lang": "Languages",
        "skill-en": "English (Business)",
        "skill-ja": "Japanese (JLPT N2)",
        "skill-hi": "Hindi (Native)",

        "section-deeptech": "SAP Architecture & Processes",
        "tech-func-title": "Core Functional (SD)",
        "tech-func-list": "<ul style='text-align:left; padding-left:20px; list-style-type:square; font-size:0.95rem; line-height:1.8; margin-top:10px;'><li>Order-to-Cash (OTC)</li><li>Pricing Procedures</li><li>Enterprise Structure</li><li>BP Master</li><li>Output Determination</li><li>Copy Control</li><li>Shipping Point Determination</li><li>Sales Document Types</li><li>ATP Check</li><li>Route Determination</li><li>etc.</li></ul>",
        "tech-abap-title": "Technical & ABAP",
        "tech-abap-list": "<ul style='text-align:left; padding-left:20px; list-style-type:square; font-size:0.95rem; line-height:1.8; margin-top:10px;'><li>RICEFW Framework</li><li>BAPI Integration</li><li>BADI Implementations</li><li>User Exits</li><li>Custom Enhancements</li><li>IDOC/EDI Monitoring</li></ul>",
        "tech-cloud-title": "Cloud & Integration",
        "tech-cloud-list": "<ul style='text-align:left; padding-left:20px; list-style-type:square; font-size:0.95rem; line-height:1.8; margin-top:10px;'><li>SAP BTP</li><li>Integration Suite</li><li>Cloud Connector</li><li>Java Connector (JCo)</li><li>J4C (Joule for Consultant)</li><li>J4D (Joule for Developer)</li><li>Third-Party API Sync</li></ul>",
        
        "section-casestudies": "Architecture Case Studies",
        "cs1-title": "Panasonic Case Study: Global E2E OTC Flow",
        "cs1-desc": "End-to-end integration mapping from inquiry to final billing, demonstrating core SAP SD capabilities.",
        "cs1-n1": "Inquiry<br><span style='font-size:0.8em;opacity:0.8'>VA11</span>",
        "cs1-n2": "Quotation<br><span style='font-size:0.8em;opacity:0.8'>VA21</span>",
        "cs1-n3": "Sales Order<br><span style='font-size:0.8em;opacity:0.8'>VA01</span>",
        "cs1-n4": "Delivery<br><span style='font-size:0.8em;opacity:0.8'>VL01N</span>",
        "cs1-n5": "PGI<br><span style='font-size:0.8em;opacity:0.8'>VL02N</span>",
        "cs1-n6": "Invoice<br><span style='font-size:0.8em;opacity:0.8'>VF01</span>",

        "modal-inq-title": "Inquiry (VA11)",
        "modal-inq-data": "<b>Concept:</b> Customer requests price/availability without legal obligation.<br><br><b>Key Tables:</b><br>• <b>VBAK:</b> Document Header Data<br>• <b>VBAP:</b> Document Item Data",
        "modal-qt-title": "Quotation (VA21)",
        "modal-qt-data": "<b>Concept:</b> A legally binding offer extended to the customer with fixed pricing and validity dates.<br><br><b>Key Tables:</b><br>• <b>VBAK:</b> Header Data<br>• <b>VBAP:</b> Item Details",
        "modal-so-title": "Sales Order (VA01)",
        "modal-so-data": "<b>Concept:</b> Customer commits to purchasing. Triggers critical background configurations.<br><br><b>Sub-Processes Triggered:</b><br>• <b>Pricing:</b> Condition Technique (VBAK, KONV/PRCD_ELEMENTS)<br>• <b>ATP Check:</b> Available-To-Promise inventory check<br>• <b>Credit Check:</b> Automatic credit control limits<br>• <b>Shipping Point:</b> Determined by Shipping Condition + Loading Group + Plant<br><br><b>Key Tables:</b><br>• <b>VBAK:</b> Header<br>• <b>VBAP:</b> Item<br>• <b>VBEP:</b> Schedule Line Data<br>• <b>VBKD:</b> Business Data",
        "modal-del-title": "Outbound Delivery (VL01N)",
        "modal-del-data": "<b>Concept:</b> Preparation for shipping. Includes picking and packing of goods.<br><br><b>Key Tables:</b><br>• <b>LIKP:</b> Delivery Document Header<br>• <b>LIPS:</b> Delivery Document Item",
        "modal-pgi-title": "Post Goods Issue (VL02N)",
        "modal-pgi-data": "<b>Concept:</b> Physical shipment of goods. Inventory is reduced and COGS (Cost of Goods Sold) is posted to Financial Accounting.<br><br><b>Key Tables:</b><br>• <b>MKPF:</b> Material Document Header<br>• <b>MSEG:</b> Material Document Item<br>• <b>VBUK / VBUP:</b> Status Tracking",
        "modal-inv-title": "Billing / Invoice (VF01)",
        "modal-inv-data": "<b>Concept:</b> Customer invoice generated and revenue posted to FI. Completes the SD lifecycle.<br><br><b>Key Tables:</b><br>• <b>VBRK:</b> Billing Document Header<br>• <b>VBRP:</b> Billing Document Item<br>• <b>BKPF / BSEG:</b> Financial Accounting Document",
        
        "cs2-title": "IDOC System Integration (Panasonic)",
        "cs2-desc": "End-to-end IDOC setup from port configuration to fully automated document exchange with external systems.",

        "modal-we21-title": "Port Definition (WE21)",
        "modal-we21-data": "<b>Purpose:</b> Defines WHERE SAP sends/receives IDOCs — the physical communication channel.<br><br><b>Panasonic Example:</b><br>• <b>Port Name:</b> TAPESTRY_PORT<br>• <b>Type:</b> File Port<br>• <b>Directory:</b> /usr/sap/interfaces/tapestry/<br><br><b>Port Types Available:</b><br>• File Port — filesystem exchange<br>• RFC Port — direct SAP-to-SAP<br>• HTTP/HTTPS — web service<br><br><b>Database Table:</b> TPROT (Port definitions)",

        "modal-we20-title": "Partner Profile (WE20)",
        "modal-we20-data": "<b>Purpose:</b> Defines WHO, WHAT, and HOW for IDOC exchange.<br><br><b>Panasonic Setup:</b><br>• <b>Partner No:</b> TAPESTRY_US<br>• <b>Partner Type:</b> KU (Customer)<br>• <b>Direction:</b> Inbound + Outbound<br>• <b>Message Types:</b> ORDERS, INVOIC, DESADV<br><br><b>Database Tables:</b><br>• EDIPP — Partner profile header<br>• EDIPIA — Inbound parameters<br>• EDIPOA — Outbound parameters",

        "modal-we57-title": "Message Type / IDOC Type Link (WE57)",
        "modal-we57-data": "<b>Purpose:</b> Maps Message Type → IDOC Type (defines the data structure for each document).<br><br><b>Example Mappings:</b><br>• ORDERS → ORDERS05<br>• INVOIC → INVOIC02<br>• DESADV → DESADV01<br><br><b>Related T-Codes:</b><br>• <b>WE31:</b> Create IDOC segments<br>• <b>WE30:</b> Create/display IDOC types<br>• <b>BD56:</b> ALE filter objects<br>• <b>WE57:</b> Message/IDOC assignment view",

        "modal-we42-title": "Process Code (WE41 / WE42)",
        "modal-we42-data": "<b>Purpose:</b> Maps IDOC type → SAP Function Module to trigger on receipt or send.<br><br>• <b>WE41:</b> Outbound process codes<br>• <b>WE42:</b> Inbound process codes<br><br><b>Inbound Example (Panasonic):</b><br>• Process Code: <b>ORDE</b><br>• Message Type: ORDERS<br>• Function Module: IDOC_INPUT_ORDERS<br>→ Automatically creates a Sales Order in SAP<br><br>⚠️ <b>Important:</b> Wrong or missing process code = Status 51 error. Always verify WE42 settings after initial config.",

        "modal-nace-title": "Output Type Configuration (NACE)",
        "modal-nace-data": "<b>Purpose:</b> Triggers automatic IDOC creation when SAP documents are saved.<br><br><b>Panasonic Config:</b><br>• Output Type: <b>EDI1</b><br>• Medium: <b>6 (EDI)</b><br>• Partner Function: SP (Sold-to Party)<br><br><b>Trigger Chain:</b><br>VF01 saved → NACE fires EDI1 → IDOC Status 01 → dispatched via port → Status 12 (dispatch OK)<br><br><b>Key Point:</b> Without NACE, IDOCs must be created manually. Proper config enables full automation.",

        "modal-idoc-ref-title": "IDOC Reference: T-Codes, Tables & Status Codes",
        "modal-idoc-ref-data": "<b>Configuration T-Codes</b><br>• <b>WE20</b> — Partner Profile setup<br>• <b>WE21</b> — Port configuration<br>• <b>WE30/31</b> — IDOC types &amp; segments<br>• <b>WE57</b> — Message/IDOC type assignment<br>• <b>WE41/42</b> — Outbound/Inbound process codes<br>• <b>NACE</b> — Output type config<br>• <b>BD64</b> — ALE Distribution Model<br><br><b>Monitoring T-Codes</b><br>• <b>WE02/WE05</b> — Display/list IDOCs<br>• <b>WE09</b> — Search IDOCs by content<br>• <b>WE19</b> — Test/reprocess IDOC manually<br>• <b>BD87</b> — Reprocess failed inbound<br>• <b>WE15</b> — Reprocess failed outbound<br><br><b>Key Database Tables</b><br>• <b>EDIDC</b> — IDOC Control Records (header)<br>• <b>EDID4</b> — IDOC Data Records (content)<br>• <b>EDIDS</b> — IDOC Status Records<br>• <b>EDIPP / EDIPIA / EDIPOA</b> — Partner profile<br>• <b>TPROT</b> — Port definitions<br><br><b>Critical Status Codes</b><br>• <b>01</b> — IDOC generated<br>• <b>03</b> — Data passed to port<br>• <b>12</b> — Dispatch OK ✅<br>• <b>16</b> — Functional ACK received ✅<br>• <b style='color:#f87171'>51</b> — Error in application ⚠️ Investigate!<br>• <b style='color:#f87171'>56</b> — IDOC with errors ⚠️ Check data<br>• <b>53</b> — Successfully posted ✅ Complete",

        "cs2-quote": "At Tapestry, I monitored inbound IDOCs daily using WE02 and WE05. When IDOCs failed with status 51, I analyzed the error at segment level, checked the partner profile configuration in WE20, verified the process code in WE42, and either resolved it functionally or raised it to the ABAP team with a detailed analysis. I also used BD87 to reprocess failed IDOCs after fixes were applied.",

        "section-certs": "Certifications",
        "cert-n2": "JLPT N2 (Aug 2025)",
        "cert-sd1": "SAP S/4HANA Sales Exploration (Mar 2025)",
        "cert-sd2": "SAP Certified Associate - S/4HANA Sales (Jan 2025)",
        "cert-agile": "Agile Software Development (Jun 2024)",
        "cert-uipath": "UiPath Certified RPA Associate (Feb 2023)",
        "cert-pmp": "PMP Fundamentals (Jan 2023)",
        "cert-devops": "DevOps Fundamentals (Nov 2022)",

        "section-contact": "Get in Touch",
        "contact-desc": "Ready to optimize your SAP processes in Japan? Let's connect!",
        "contact-location": "Tokyo, Japan",
        "contact-linkedin": "LinkedIn Profile",
        "contact-calendar-desc": "Want to discuss an opportunity? Book a 30-minute chat with me!",
        "btn-calendar": "🗓️ Book an Appointment"
    },
    ja: {
        "mascot-hero": "私の東京テーマパークへようこそ！ごゆっくりお楽しみください！",
        "mascot-about": "インドから東京に至る私のキャリアの軌跡をご覧ください！",
        "mascot-experience": "ここはビジネス街です。私のSAP経歴をご覧ください！",
        "mascot-skills": "テックアーケードへようこそ！スキルゲージがチャージされます！",
        "mascot-deeptech": "お台場エンジニアリングベイ！SAPのコアアーキテクチャを展開しています。",
        "mascot-certifications": "知識の神社です。私の資格証明書が奉納されています。",
        "mascot-contact": "スカイツリーから発信中！いつでもご連絡ください！",

        "hero-greeting": "こんにちは、",
        "hero-name": "グプタ・ディラジュ",
        "hero-title": "SAP SD バイリンガルコンサルタント",
        "hero-subtitle": "東京在住 | OTC、データ移行・導入、テスト、展開（ロールアウト）、運用サポートの専門家",
        "hero-activate": "Discover ➔ Prepare ➔ Explore ➔ Realize ➔ Deploy ➔ Run",
        "btn-english": "📄 英語レジュメ (CV)",
        "btn-rirekisho": "📝 履歴書 (Rirekisho)",
        "btn-shokumu": "💼 職務経歴書 (Details)",

        "section-about": "自己PR",
        "about-p1": "私のキャリアは、インドの製造業での購買担当からスタートしました。仕入先との価格交渉や在庫管理に従事するなかで、Zoho Inventoryの導入プロジェクトを自ら主導し、在庫回転率20%改善・保管コスト15%削減を達成しました。この経験を通じて「ITの力で業務を変える」という面白さを実感し、より大きなシステムに携わりたいという思いが強まっていきました。",
        "about-p2": "同時に、日本語を独学で本格的に学び始めました。デリー大学の東アジア研究学科でディプロマを2段階取得し、さらに日本語能力試験N2の取得に向けて毎日学習を継続しました。単に語学資格を目指すというよりも、日本のビジネス文化や仕事の進め方を深く理解し、日本企業の中で本当に役立てる人材になりたいという一心でした。",
        "about-p3": "富士通インドでは、日本のクライアントに対して日本語で直接対応する業務を担当しました。最初は専門用語や敬語表現に苦労しましたが、会議を録音して振り返り、業務マニュアルを繰り返し読み込むことで徐々に自信をつけていきました。また、UiPathを活用した調達業務の自動化にも取り組み、ITと語学を組み合わせた業務改善の手応えを感じることができました。",
        "about-p4": "キャップジェミニに入社した当初は、SAP SDの専門知識が十分ではありませんでした。しかし、ATPの設定・価格決定・出荷ポイントなど基礎から毎日自己学習を積み重ね、ベテランコンサルタントの作業を観察しながらベストプラクティスを吸収していきました。その結果、入社から半年でSD基本設定を単独担当できるレベルまで成長。1年後にはクライアントからの問い合わせに対する解決スピードが大幅に向上し、「対応が速くなった」「説明がわかりやすい」と言っていただけるようになりました。Yamaha Music・Panasonic・GC Dentalなど複数のプロジェクトを経験することで、ロールアウト・データ移行・UAT・サポートといったSAP導入の全フェーズを体験できたことは、私の最大の財産です。",
        "about-p5": "2026年3月、東京に拠点を移し、インドサクラ ジャパンに入社しました。インドでのリモート対応から、日本国内での常駐対応へと環境が変わり、より直接的に日本のクライアントと向き合う機会をいただいています。現地での実務経験を積みながら、SAP MMおよびSAP BTPの習得にも取り組んでいます。SDだけでなく、MM・BTPを横断した複合的な提案ができるコンサルタントを目指しています。私の強みは「学ぶ速さ」と「日本語と英語を使ったチームへの貢献」です。どのような環境でも、まず自分から動き、周囲と連携しながら課題を解決することを大切にしています。チームの一員として信頼されること、そしてクライアントに「この人に頼んでよかった」と思っていただけることが、私の仕事の原動力です。",

        "section-experience": "職務経歴",
        "exp-indosakura-date": "2026年3月 - 現在",
        "exp-indosakura-title": "SAP SD バイリンガルコンサルタント",
        "exp-indosakura-company": "インドサクラ ソフトウェア ジャパン | 東京",
        "exp-indosakura-b1": "OTCプロセス全体と価格決定表（Pricing Procedures）をカバーするL2/L3サポートを提供。",
        "exp-indosakura-b2": "ビジネス課題をシステム要件へ変換し、日英でのヒアリングを実施。",
        "exp-indosakura-b3": "高度な出力管理（Output Determination）および出荷ポイント設定の課題解決。",

        "exp-capgemini-date": "2023年7月 - 2026年2月",
        "exp-capgemini-title": "SAP SD バイリンガルコンサルタント",
        "exp-capgemini-company": "キャップジェミニ インド (日本市場担当)",
        "exp-capgemini-b1": "Tapestry: IDOC障害の分析とユーザーエグジット（User Exits）の設計など、インシデント解決を主導。",
        "exp-capgemini-b2": "Yamaha Music: グローバルテンプレート向けに企業構造（Enterprise Structure）とコピコントロールをマッピング。",
        "exp-capgemini-b3": "Panasonic: レガシーからS/4HANAへの大規模データ移行、およびBAPIの実装を実行。",
        "exp-capgemini-b4": "GC Dental: Panayaを利用し、E2EのOTCプロセスとRICEFW開発を含むUAT完了を支援。",

        "exp-fujitsu-date": "2022年1月 - 2023年7月",
        "exp-fujitsu-title": "テクニカルサービス担当",
        "exp-fujitsu-company": "富士通インド (日本市場担当)",
        "exp-fujitsu-b1": "グローバルパートナー向けのバイリンガル調達処理をサポート。",
        "exp-fujitsu-b2": "UiPath RPAを使用してPOおよび見積書のプロセスを自動化。",

        "exp-gupta-date": "2017年8月 - 2019年4月",
        "exp-gupta-title": "購買担当",
        "exp-gupta-company": "Gupta Industrial Hardware | インド",
        "exp-gupta-b1": "Zoho Inventoryの導入およびBPマスタの整合性調整を主導。",
        "exp-gupta-b2": "在庫回転率を20%改善し、保管コストを15%削減。",

        "section-skills": "技術力 (スキル)",
        "skill-title-sap": "SAPモジュール",
        "skill-sd": "S/4HANA SD (販売管理)",
        "skill-mm": "SAP MM (基礎)",
        "skill-btp": "SAP BTP (学習中)",
        "skill-title-integration": "統合・テスト",
        "skill-idoc": "IDOC / EDI / API連携",
        "skill-panaya": "Panaya UAT",
        "skill-rpa": "UiPath RPA",
        "skill-title-lang": "語学",
        "skill-en": "英語 (ビジネス)",
        "skill-ja": "日本語 (JLPT N2)",
        "skill-hi": "ヒンディー語 (母語)",

        "section-deeptech": "SAPプロセスと技術アーキテクチャ",
        "tech-func-title": "コア機能 (SDプロセス)",
        "tech-func-list": "<ul style='text-align:left; padding-left:20px; list-style-type:square; font-size:0.95rem; line-height:1.8; margin-top:10px;'><li>Order-to-Cash (OTC)</li><li>価格決定（Pricing）</li><li>企業構造（Enterprise Structure）</li><li>BPマスタ</li><li>出力決定（Output Determination）</li><li>コピコントロール</li><li>出荷ポイント決定</li><li>販売伝票タイプ</li><li>ATPチェック</li><li>ルート決定（Route Determination）</li><li>など</li></ul>",
        "tech-abap-title": "ABAP / 技術的専門知識",
        "tech-abap-list": "<ul style='text-align:left; padding-left:20px; list-style-type:square; font-size:0.95rem; line-height:1.8; margin-top:10px;'><li>RICEFWフレームワーク</li><li>BAPI連携</li><li>BADI実装</li><li>ユーザーエグジット（User Exits）</li><li>カスタム機能拡張</li><li>IDOC/EDIモニタリング</li></ul>",
        "tech-cloud-title": "クラウド / インテグレーション",
        "tech-cloud-list": "<ul style='text-align:left; padding-left:20px; list-style-type:square; font-size:0.95rem; line-height:1.8; margin-top:10px;'><li>SAP BTP</li><li>Integration Suite</li><li>Cloud Connector</li><li>Java Connector (JCo)</li><li>J4C (Joule for Consultant)</li><li>J4D (Joule for Developer)</li><li>サードパーティAPI連携</li></ul>",

        "section-casestudies": "アーキテクチャ事例 (Case Studies)",
        "cs1-title": "パナソニック 事例：グローバル E2E OTCフロー",
        "cs1-desc": "引き合いから最終請求までのエンドツーエンド統合マッピング。SAP SDのコア機能を示します。",
        "cs1-n1": "引き合い<br><span style='font-size:0.8em;opacity:0.8'>VA11</span>",
        "cs1-n2": "見積<br><span style='font-size:0.8em;opacity:0.8'>VA21</span>",
        "cs1-n3": "受注<br><span style='font-size:0.8em;opacity:0.8'>VA01</span>",
        "cs1-n4": "出荷伝票<br><span style='font-size:0.8em;opacity:0.8'>VL01N</span>",
        "cs1-n5": "出庫転記 (PGI)<br><span style='font-size:0.8em;opacity:0.8'>VL02N</span>",
        "cs1-n6": "請求<br><span style='font-size:0.8em;opacity:0.8'>VF01</span>",

        "modal-inq-title": "引き合い (VA11)",
        "modal-inq-data": "<b>概要:</b> 法的義務を伴わない、顧客からの価格・在庫に関する問い合わせ。<br><br><b>主要テーブル:</b><br>• <b>VBAK:</b> 販売管理ヘッダデータ<br>• <b>VBAP:</b> 販売管理明細データ",
        "modal-qt-title": "見積 (VA21)",
        "modal-qt-data": "<b>概要:</b> 固定価格と有効期限を含む、顧客への法的拘束力のあるオファー。<br><br><b>主要テーブル:</b><br>• <b>VBAK:</b> ヘッダデータ<br>• <b>VBAP:</b> 明細データ",
        "modal-so-title": "受注 (VA01)",
        "modal-so-data": "<b>概要:</b> 顧客の購入確定。このステップで重要なバックグラウンド設定がトリガーされます。<br><br><b>主要なサブプロセス:</b><br>• <b>価格決定:</b> 条件テクニック (VBAK, KONV/PRCD_ELEMENTS)<br>• <b>ATPチェック:</b> 利用可能在庫確認<br>• <b>与信管理:</b> 自動与信チェック<br>• <b>出荷ポイント決定:</b> 出荷条件 + 荷役グループ + プラント<br><br><b>主要テーブル:</b><br>• <b>VBAK:</b> ヘッダ<br>• <b>VBAP:</b> 明細<br>• <b>VBEP:</b> 納入日程行データ<br>• <b>VBKD:</b> ビジネスデータ",
        "modal-del-title": "出荷伝票 (VL01N)",
        "modal-del-data": "<b>概要:</b> 出荷の準備。ピッキングと梱包を含みます。<br><br><b>主要テーブル:</b><br>• <b>LIKP:</b> 出荷伝票ヘッダ<br>• <b>LIPS:</b> 出荷伝票明細",
        "modal-pgi-title": "出庫転記 (VL02N)",
        "modal-pgi-data": "<b>概要:</b> 商品の物理的出荷。在庫が減少し、売上原価（COGS）が財務会計に転記されます。<br><br><b>主要テーブル:</b><br>• <b>MKPF:</b> 入出庫伝票ヘッダ<br>• <b>MSEG / MATDOC:</b> 入出庫伝票明細<br>• <b>VBUK / VBUP:</b> ステータス管理",
        "modal-inv-title": "請求 / インボイス (VF01)",
        "modal-inv-data": "<b>概要:</b> 顧客の請求書が生成され、収益がFIに転記されます。SDライフサイクルが完了します。<br><br><b>主要テーブル:</b><br>• <b>VBRK:</b> 請求伝票ヘッダ<br>• <b>VBRP:</b> 請求伝票明細<br>• <b>BKPF / BSEG:</b> 財務会計伝票",

        "cs2-title": "IDOCによるシステム統合 (パナソニック)",
        "cs2-desc": "ポート設定から外部システムとの完全自動伝票交換まで、エンドツーエンドのIDOCセットアップ。",

        "modal-we21-title": "ポート定義 (WE21)",
        "modal-we21-data": "<b>目的:</b> IDOCの送受信先（物理的な通信チャネル）を定義します。<br><br><b>パナソニック設定例:</b><br>• <b>ポート名:</b> TAPESTRY_PORT<br>• <b>タイプ:</b> ファイルポート<br>• <b>ディレクトリ:</b> /usr/sap/interfaces/tapestry/<br><br><b>利用可能なポートタイプ:</b><br>• ファイルポート — ファイルシステム経由<br>• RFCポート — SAP間直接接続<br>• HTTP/HTTPS — Webサービス<br><br><b>データベーステーブル:</b> TPROT",

        "modal-we20-title": "パートナープロファイル (WE20)",
        "modal-we20-data": "<b>目的:</b> IDOC交換の相手先・内容・方法を定義します。<br><br><b>パナソニック設定:</b><br>• <b>パートナー番号:</b> TAPESTRY_US<br>• <b>パートナータイプ:</b> KU（得意先）<br>• <b>方向:</b> 受信 + 送信<br>• <b>メッセージタイプ:</b> ORDERS, INVOIC, DESADV<br><br><b>データベーステーブル:</b><br>• EDIPP — パートナープロファイルヘッダ<br>• EDIPIA — 受信パラメータ<br>• EDIPOA — 送信パラメータ",

        "modal-we57-title": "メッセージタイプ / IDOCタイプリンク (WE57)",
        "modal-we57-data": "<b>目的:</b> メッセージタイプ → IDOCタイプのマッピング（各伝票のデータ構造定義）。<br><br><b>マッピング例:</b><br>• ORDERS → ORDERS05<br>• INVOIC → INVOIC02<br>• DESADV → DESADV01<br><br><b>関連Tコード:</b><br>• <b>WE31:</b> IDOCセグメント作成<br>• <b>WE30:</b> IDOCタイプ表示/作成<br>• <b>BD56:</b> ALEフィルタオブジェクト",

        "modal-we42-title": "プロセスコード (WE41 / WE42)",
        "modal-we42-data": "<b>目的:</b> IDOCタイプ → 実行するSAP機能モジュールのマッピング。<br><br>• <b>WE41:</b> 送信プロセスコード<br>• <b>WE42:</b> 受信プロセスコード<br><br><b>受信例（パナソニック）:</b><br>• プロセスコード: <b>ORDE</b><br>• メッセージタイプ: ORDERS<br>• 機能モジュール: IDOC_INPUT_ORDERS<br>→ 受注を自動的に作成<br><br>⚠️ <b>重要:</b> プロセスコードが誤っている場合、ステータス51エラーが発生します。",

        "modal-nace-title": "出力タイプ設定 (NACE)",
        "modal-nace-data": "<b>目的:</b> SAP伝票保存時にIDOC自動生成をトリガーします。<br><br><b>パナソニック設定:</b><br>• 出力タイプ: <b>EDI1</b><br>• 媒体: <b>6（EDI）</b><br>• 相手先機能: SP（受注先）<br><br><b>トリガーチェーン:</b><br>VF01保存 → NACE EDI1起動 → IDOC ステータス01 → ポート経由送信 → ステータス12<br><br><b>ポイント:</b> NACE設定なしでは手動でIDOCを作成する必要があります。",

        "modal-idoc-ref-title": "IDOCリファレンス: Tコード・テーブル・ステータスコード",
        "modal-idoc-ref-data": "<b>設定Tコード</b><br>• <b>WE20</b> — パートナープロファイル<br>• <b>WE21</b> — ポート設定<br>• <b>WE30/31</b> — IDOCタイプ/セグメント<br>• <b>WE57</b> — MSG/IDOCタイプ割当<br>• <b>WE41/42</b> — 送受信プロセスコード<br>• <b>NACE</b> — 出力タイプ設定<br>• <b>BD64</b> — ALEディストリビューションモデル<br><br><b>監視Tコード</b><br>• <b>WE02/WE05</b> — IDOC表示/一覧<br>• <b>WE09</b> — コンテンツ検索<br>• <b>WE19</b> — テスト/再処理<br>• <b>BD87</b> — 受信失敗IDOCの再処理<br>• <b>WE15</b> — 送信失敗IDOCの再処理<br><br><b>主要データベーステーブル</b><br>• <b>EDIDC</b> — IDOCコントロールレコード（ヘッダ）<br>• <b>EDID4</b> — IDOCデータレコード（内容）<br>• <b>EDIDS</b> — IDOCステータスレコード<br>• <b>EDIPP/EDIPIA/EDIPOA</b> — パートナープロファイル<br>• <b>TPROT</b> — ポート定義<br><br><b>重要ステータスコード</b><br>• <b>01</b> — IDOC生成済<br>• <b>12</b> — 送信OK ✅<br>• <b>16</b> — 機能確認応答受信 ✅<br>• <b style='color:#f87171'>51</b> — アプリケーションエラー ⚠️<br>• <b style='color:#f87171'>56</b> — エラーあり ⚠️<br>• <b>53</b> — 正常転記 ✅",

        "section-certs": "資格・認定",
        "cert-n2": "日本語能力試験 N2 (2025年8月)",
        "cert-sd1": "SAP S/4HANA Sales Exploration (2025年3月)",
        "cert-sd2": "SAP Certified Associate - S/4HANA Sales (2025年1月)",
        "cert-agile": "Agile Software Development (2024年6月)",
        "cert-uipath": "UiPath Certified RPA Associate (2023年2月)",
        "cert-pmp": "PMP Fundamentals (2023年1月)",
        "cert-devops": "DevOps Fundamentals (2022年11月)",

        "section-contact": "お問い合わせ",
        "contact-desc": "日本でのSAPプロセス最適化にご興味はありますか？ぜひご連絡ください！",
        "contact-location": "日本、東京",
        "contact-linkedin": "LinkedIn プロフィール",
        "contact-calendar-desc": "プロジェクトのご相談はありませんか？30分のカジュアル面談を予約する：",
        "btn-calendar": "🗓️ 面談を予約する"
    }
};
